export const answers = [
	'Ja.',
	'Nein.',
	'67.',
	'Wahrscheinlich nicht.',
	'Wahrscheinlich schon.',
	'Keine Ahnung.',
	'Wenn du das willst, dann ja.',
	'Vielleicht.',
	'Auf jeden Fall!',
	'Auf gar keinen Fall...',
	'Das kommt gar nicht in Frage.',
	'Warum fragst du sowas überhaupt..',
	'Denke nicht.',
	'Definitiv.',
	'Absolut nicht.',
	'42.',
	'Frag mich später nochmal.',
	'Die Sterne sagen ja.',
	'Die Sterne sagen nein.',
	'Eher unwahrscheinlich.',
	'Zu 100%.',
	'Niemals im Leben.',
	'Ich würde nicht drauf wetten.',
	'Klingt nach einer schlechten Idee.',
	'Na klar, wieso auch nicht.',
	'Lieber nicht.',
	'Das steht in den Sternen.',
	'Ganz sicher nicht.',
	'Ich sag nur: vielleicht.',
	'Frag nochmal, aber ehrlich diesmal.',
	'Ist das dein Ernst?',
	'Ich bin nur ein Ball, keine Ahnung.',
	'Schwer zu sagen.',
	'Konzentriere dich und frag nochmal.',
	'Meine Antwort: es kommt darauf an.',
	'Ha! Gute Frage.',
	'Lass mich kurz nachdenken... nein.',
	'Da bin ich mir sicher: ja.',
	'Bestimmt nicht.',
	'Könnte sein.',
	'Ich glaube schon.',
	'Ich glaube eher nicht.',
	'Das würde ich lassen.',
	'Mach es einfach.',
	'Ich, als KI, kann das nicht beantworten.'
];
